export const storyItems = [
  {
    id: 1,
    text: 'Andrey Yusupov initiated the creation and headed a consumer cooperative with neighbors to jointly purchase products from farmers. The roles were distributed among the members of the cooperative: One takes the groceries today, another tomorrow',
    year: '2015',
    img: '/images/ourstory/photo1.png',
    // img760: '/images/RoadMap/760/1.png',
    // img390: '/images/RoadMap/390/1.png',
    style: '',
  },
  {
    id: 2,
    text: 'Our successful experience quickly spread throughout the city, and many people asked for help in opening their own cooperatives. To simplify ordering, accounting and document management, we have organized the development of our first IT platform. Consumer cooperatives have been launched at enterprises.',
    year: '2016',
    img: '/images/ourstory/photo2.png',
    // img760: '/images/RoadMap/760/2.png',
    // img390: '/images/RoadMap/390/2.png',
    style: 'reverse',
  },
  {
    id: 3,
    text: 'Our first office has been opened. Our IT solutions are becoming more complicated: solutions for automation of cross-docking, first - nd last-mile delivery solution have appeared, a solution for order terminals in offices and enterprises has been launched, packaging and promotional materials have been developed',
    year: '2017',
    img: '/images/ourstory/photo3.png',
    // img760: '/images/RoadMap/760/1.png',
    // img390: '/images/RoadMap/390/1.png',
    style: '',
  },
  {
    id: 4,
    text: 'In order to scale to other regions and countries, the commercial organization EdaEco was created. Initially, there was delivery only to enterprises. Then we launched targeted home delivery. The first eco-points were opened - centers for issuing orders in cafes',
    year: '2018',
    img: '/images/ourstory/photo4.png',
    // img760: '/images/RoadMap/760/2.png',
    // img390: '/images/RoadMap/390/2.png',
    style: 'reverse',
  },
  {
    id: 5,
    text: 'Andrey Yusupov created united cooperatives - United Cooperatives - the beginning of the history of UNCO. The first farm-to-table business in Berlin has been launched https://unco.club',
    year: '2019',
    img: '/images/ourstory/photo5.png',
    // img760: '/images/RoadMap/760/1.png',
    // img390: '/images/RoadMap/390/1.png',
    style: '',
  },
  {
    id: 6,
    text: 'We have developed a new version of our UNCO Farmer`s Corner business solution in the `white label` format. A new version of our IT solution has been released.',
    year: '2019',
    img: '/images/ourstory/photo6.png',
    // img760: '/images/RoadMap/760/2.png',
    // img390: '/images/RoadMap/390/2.png',
    style: 'reverse',
  },
  {
    id: 7,
    text: 'Launched in Germany "white label"',
    year: '2020',
    img: '/images/ourstory/photo7.png',
    // img760: '/images/RoadMap/760/1.png',
    // img390: '/images/RoadMap/390/1.png',
    style: '',
  },
  {
    id: 8,
    text: 'Launched in Italy "white label", the development of a conceptually new eco-friendly and Worldwide available business solution and IT solution has begun',
    year: '2022',
    img: '/images/ourstory/photo8.png',
    // img760: '/images/RoadMap/760/2.png',
    // img390: '/images/RoadMap/390/2.png',
    style: 'reverse',
  },
  {
    id: 9,
    text: 'The "white label" was launched in Serbia, the platform was launched https://unco.market - the first solution within the framework of the "UNCO Global" concept',
    year: '2023',
    img: '/images/ourstory/photo9.png',
    // img760: '/images/RoadMap/760/1.png',
    // img390: '/images/RoadMap/390/1.png',
    style: '',
  },
  {
    id: 10,
    text: 'Landing pages have been launched https://foodfutures.net https://foodfutures.club https://unco.market https://foodnft.org https://unco.bio https://unco.trade Developed and proposed for publication \"UNCO Food Futures for Food Retail\" and \"UNCO Food Futures for HoReCa\"',
    year: '2024',
    img: '/images/ourstory/photo10.png',
    // img760: '/images/RoadMap/760/2.png',
    // img390: '/images/RoadMap/390/2.png',
    style: 'reverse',
  },
];
